language: ruby
rvm:
  - 2.0.0
  - 2.2.3
  - 2.3.3
  - 2.4.0-rc1
  - jruby-9.0.3.0
  - jruby-9.1.6.0
  - jruby-head
  - ruby-head
before_script:
  - bundle update
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true
script: bundle exec rspec spec
sudo: false
cache: bundler
addons:
  code_climate:
    repo_token: fab8afb587984cc2f6100be9c660e966ac3fb5e113458fb381267bfffcef15fe
