language: ruby
rvm:
  - jruby-19mode
  - rbx-19mode
  - 2.2
  - jruby
script: bundle exec rspec spec

addons:
  code_climate:
    repo_token: fab8afb587984cc2f6100be9c660e966ac3fb5e113458fb381267bfffcef15fe
