language: ruby
rvm:
  - jruby-1.7.23
  - rbx-2.5.8
  - 2.2
  - jruby-9.0.4.0
  - jruby-head
  - ruby-head
before_script:
  - bundle update
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
script: bundle exec rspec spec
sudo: false
cache: bundler
addons:
  code_climate:
    repo_token: fab8afb587984cc2f6100be9c660e966ac3fb5e113458fb381267bfffcef15fe
